version: '3.8'

services:
  chord-node:
    build:
      context: .. # Context points to the root directory
      dockerfile: docker/Dockerfile.node
    ports:
      - "8080:8080"
      - "8081:8080"
    environment:
      BASE_PORT: 8080
      IS_INTRODUCER: "${IS_INTRODUCER:-false}"
      INTRODUCER_ADDRESS: "chord-introducer:8080"
    deploy:
      replicas: ${NUM_NODES:-10}
    networks:
      - chord-network


  test-suite:
    build:
      context: ../ # Context points to the root directory
      dockerfile: docker/Dockerfile.client
    depends_on:
      - chord-node
    networks:
      - chord-network
    environment:
      NUM_NODES: "${NUM_NODES:-10}"
    command: ["./test_suite"]

networks:
  chord-network:
    driver: bridge
