# Use Go 1.22
FROM golang:1.22

# Install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o chord_dns .

# Expose the application port
EXPOSE 8001

# Add healthcheck
HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8001/health || exit 1

# Command to run the application
CMD ["./chord_dns"]