version: '3.8'

services:
  chord-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    ports:
      - "${NODE_PORT}:8080"  # Assign dynamic ports
    environment:
      BASE_PORT: 8080        # Optional: starting base port
      NUM_NODES: 1          # Optional: number of nodes
    command: ["./chord_dns", "-all"] # Override CMD for tests
    networks:
      - chord-network
    deploy:
      replicas: 10           # Spin up multiple nodes dynamically

  test-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    depends_on:
      - chord-node
    networks:
      - chord-network

networks:
  chord-network:
    driver: bridge
