# Base image for Go
FROM golang:1.20

# Set the working directory
WORKDIR /app

# Copy the source code into the container
COPY . .

# Enable Go modules
ENV GO111MODULE=on

# Build the Go application
RUN go build -o chord_dns .

# Expose the application port
EXPOSE 8080

# Run the application by default
CMD ["./chord_dns"]

