FROM golang:1.23-alpine

WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the code
COPY . .

# Build the application
RUN go build -o chord_dns

# The port will be specified in docker-compose.yml
EXPOSE 8001

CMD ["./chord_dns"]